sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t lacisoft/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lacisoft/multi-docker-test npm run test -- --coverage

after_success:
  - docker build -t lacisoft/multi-client ./client
  - docker build -t lacisoft/multi-nginx ./nginx
  - docker build -t lacisoft/multi-server ./server
  - docker build -t lacisoft/multi-worker ./worker

  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lacisoft/multi-client
  - docker push lacisoft/multi-nginx
  - docker push lacisoft/multi-server
  - docker push lacisoft/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "proj5-frontend"
#  env: "Proj5Frontend-env"
#  bucket_name: "elasticbeanstalk-us-east-1-113564655697"
#  bucket_path: "proj5-frontend"
#  on:
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"